Add Date to Terms and Conditions
Human-Connection-Community/Human-Connection-New-20201003 pull request #1535
Opened 2020-10-05 07:22 UTC by Tirokk

> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-09-09T12:09:17Z" title="Monday, September 9th 2019, 2:09:17 pm +02:00">Sep 9, 2019</time>_
_Closed <time datetime="2019-09-12T16:10:11Z" title="Thursday, September 12th 2019, 6:10:11 pm +02:00">Sep 12, 2019</time>_
---

## 🍰 Pullrequest
When confirming the current VERSION of the terms and conditions, the DATE is also saved (termsAndConditionsAgreedAt). 

### Issues
- fixes https://github.com/Human-Connection/Human-Connection/pull/1556

2020-10-06 19:44 UTC, Tirokk commented on backend/src/middleware/slugifyMiddleware.spec.js
> -import { createTestClient } from 'apollo-server-testing'
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-09T13:05:41Z" title="Monday, September 9th 2019, 3:05:41 pm +02:00">Sep 9, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -89,8 +89,8 @@ describe('slugify', () => {
   })
 
   describe('SignupVerification', () => {
-    const mutation = `mutation($password: String!, $email: String!, $name: String!, $slug: String, $nonce: String!, $termsAndConditionsAgreedVersion: String!) {
-      SignupVerification(email: $email, password: $password, name: $name, slug: $slug, nonce: $nonce, termsAndConditionsAgreedVersion: $termsAndConditionsAgreedVersion) { 
+    const mutation = `mutation($password: String!, $email: String!, $name: String!, $slug: String, $nonce: String!, $termsAndConditionsAgreedVersion: String!, termsAndConditionsAgreedAt: String) {
```


No, the `termsAndConditionsAgreedAt` should *not* be supplied by the user. We don't care what the user tells us, what date it is. We **know** the date *on the server*. So, in the `SignupVerification` resolver, we set the `termsAndConditionsAgreedAt` manually.

2020-10-06 19:46 UTC, Tirokk commented
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-09-10T06:26:19Z" title="Tuesday, September 10th 2019, 8:26:19 am +02:00">Sep 10, 2019</time>_

---


i have it now so ... that the date is saved to the version. however at no place can be displayed. even :4000 cannot display it .. but :7687 there i see it at the user ...

2020-10-06 19:47 UTC, Tirokk commented
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-11T15:01:45Z" title="Wednesday, September 11th 2019, 5:01:45 pm +02:00">Sep 11, 2019</time>_

---


> maybe for consistency we keep this in `backend/src/middleware/dateTimeMiddleware.js`
> although, we are having a bug with `createdAt` so what do ya'll think?

never mind @ogerly, I'll refactor to use `createdAt` and `updatedAt` in the resolvers themselves :smile:

2020-10-08 08:27 UTC, Mogge requested changes
@ogerly I think you got me wrong: The server should know the current date already. So we don't have to expose the `termsAndConditionsAgreedAt` as input param to the client. The attribute is certainly read-only, maybe not even that.

2020-10-08 08:30 UTC, Mogge requested changes
maybe for consistency we keep this in `backend/src/middleware/dateTimeMiddleware.js`
although, we are having a bug with `createdAt` so what do ya'll think?

2020-10-08 12:26 UTC, closed without merging