Fix disappearing embeds on comments
Human-Connection-Community/Human-Connection-New-20201003 pull request #1618
Opened 2020-10-05 07:28 UTC by Tirokk

> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-09-17T15:52:03Z" title="Tuesday, September 17th 2019, 5:52:03 pm +02:00">Sep 17, 2019</time>_
_Merged <time datetime="2019-09-18T12:40:03Z" title="Wednesday, September 18th 2019, 2:40:03 pm +02:00">Sep 18, 2019</time>_
---

- by passing the prop content to the content-viewer with the comments
content if it is less than 180 characters or if it's different from the
contentExcerpt

## 🍰 Pullrequest

### Issues

- fixes #1547 

### Todo

- [X] None

2020-10-06 19:53 UTC, Tirokk commented on webapp/components/Comment.vue
> +          />
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-17T16:43:41Z" title="Tuesday, September 17th 2019, 6:43:41 pm +02:00">Sep 17, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -39,18 +39,27 @@
         />
       </div>
       <div v-show="!openEditCommentMenu">
-        <div v-if="isCollapsed" v-html="comment.contentExcerpt" style="padding-left: 40px;" />
+        <content-viewer
+          v-if="comment.content.length < 180"
+          :content="comment.content"
+          class="padding-left"
+        />
         <div
           v-show="comment.content !== comment.contentExcerpt && comment.content.length > 180"
           style="text-align: right;  margin-right: 20px; margin-top: -12px;"
         >
+          <content-viewer
+            v-if="isCollapsed"
+            :content="comment.contentExcerpt"
+            class="padding-left"
+          />
```


@mattwr18 I don't understand why we have `content` twice now, and the `contentExcerpt` here..

2020-10-06 19:54 UTC, Tirokk commented on webapp/components/Comment.spec.js
> +          it.skip('renders comment data', () => {
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-09-18T10:03:03Z" title="Wednesday, September 18th 2019, 12:03:03 pm +02:00">Sep 18, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -103,7 +104,7 @@ describe('Comment.vue', () => {
             getters['auth/isModerator'] = () => true
           })
 
-          it('renders comment data', () => {
+          it.skip('renders comment data', () => {
```


@mattwr18 adding technical debt :skull_and_crossbones:

2020-10-08 08:31 UTC, Mogge requested changes
This looks good! 

![Looks good](https://media.giphy.com/media/LXHJRRjnviw7e/giphy.gif)

But why are the comments now right aligned before I click on `show more`?

![Screenshot - 2019-09-17T184401 507](https://user-images.githubusercontent.com/2110676/65061899-26670000-d97b-11e9-9510-2187e8e2d675.png)

2020-10-08 08:31 UTC, Mogge approved these changes
![Ok](https://media.giphy.com/media/720g7C1jz13wI/giphy.gif)

2020-10-08 12:28 UTC, closed without merging