Language will be saved in the database of the user during registration
Human-Connection-Community/Human-Connection-New-20201003 pull request #1927
Opened 2020-10-05 08:13 UTC by Tirokk

> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-16T13:14:20Z" title="Wednesday, October 16th 2019, 3:14:20 pm +02:00">Oct 16, 2019</time>_
_Merged <time datetime="2019-10-18T13:11:05Z" title="Friday, October 18th 2019, 3:11:05 pm +02:00">Oct 18, 2019</time>_
---

## 🍰 Pullrequest
set language will be saved in the database of the user during registration 
eingestellte sprache wird beim registrieren in die datenbank zum user gespeichert 

### issuse
#1929 

### group
dieses Problem ist ein Teil von https://github.com/Human-Connection/Human-Connection/issues/1931

![FireShot Capture 094 - Human Connection - Human Connection - localhost](https://user-images.githubusercontent.com/1324583/66922568-97a3dc80-f027-11e9-8eb4-44813e75f105.png)

![FireShot Capture 093 - bolt___localhost_7687 - Neo4j Browser - localhost](https://user-images.githubusercontent.com/1324583/66922030-8e664000-f026-11e9-9dc1-fb03a853bd0f.png)

2020-10-06 20:47 UTC, Tirokk commented on backend/src/models/User.js
> +  locale: {
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-17T10:48:50Z" title="Thursday, October 17th 2019, 12:48:50 pm +02:00">Oct 17, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -109,4 +109,8 @@ module.exports = {
     type: 'boolean',
     default: false,
   },
+  language: {
```


If `Vuex-i18n` calls it `locale` maybe we want to call it `locale` in the backend, too?

2020-10-06 20:47 UTC, Tirokk commented on webapp/components/Registration/CreateUserAccount.vue
> +            locale,
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-17T10:49:55Z" title="Thursday, October 17th 2019, 12:49:55 pm +02:00">Oct 17, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -154,10 +156,19 @@ export default {
       const { name, password, about } = this.formData
       const { email, nonce } = this
       const termsAndConditionsAgreedVersion = VERSION
+      const language = this.$i18n.locale()
       try {
         await this.$apollo.mutate({
           mutation: SignupVerificationMutation,
-          variables: { name, password, about, email, nonce, termsAndConditionsAgreedVersion },
+          variables: {
+            name,
+            password,
+            about,
+            email,
+            nonce,
+            termsAndConditionsAgreedVersion,
+            language,
```


Could `LocaleSwitch` component also update the current user's locale?

2020-10-06 20:47 UTC, Tirokk commented on webapp/graphql/Registration.js
> +    $locale: String
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-17T10:50:32Z" title="Thursday, October 17th 2019, 12:50:32 pm +02:00">Oct 17, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -7,6 +7,7 @@ export const SignupVerificationMutation = gql`
     $password: String!
     $about: String
     $termsAndConditionsAgreedVersion: String!
+    $language: String
```


This is going in the right direction. Could you also add `locale` as allowed input parameter to `UpdateUser`, please?

2020-10-06 20:47 UTC, Tirokk commented on webapp/components/Registration/CreateUserAccount.vue
> +            locale,
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-17T16:33:10Z" title="Thursday, October 17th 2019, 6:33:10 pm +02:00">Oct 17, 2019</time>_

---


ich hatte sie schon in der arbeit. kam aber nicht zu guten ergebnissen. wäre schön wenn ich das im folge PR anpassen könnte wenn es passt und ein besserer weg ist :)

2020-10-06 20:47 UTC, Tirokk commented on webapp/graphql/Registration.js
> +    $locale: String
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-17T16:34:14Z" title="Thursday, October 17th 2019, 6:34:14 pm +02:00">Oct 17, 2019</time>_

---


mit dem nächsten PR würde ich das gern + anwendungsfall erledingen um die sache nicht wieder so in die länge zu ziehen

2020-10-06 20:47 UTC, Tirokk commented on backend/src/models/User.js
> +  locale: {
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-17T16:35:15Z" title="Thursday, October 17th 2019, 6:35:15 pm +02:00">Oct 17, 2019</time>_

---


ja

2020-10-06 20:47 UTC, Tirokk commented on webapp/graphql/Registration.js
> +    $locale: String
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-10-17T22:34:56Z" title="Friday, October 18th 2019, 12:34:56 am +02:00">Oct 18, 2019</time>_

---


@ogerly OK, could you rename `language` to `locale`? I'm OK to merge this then.

@mattwr18 what is the better name here? :point_up: I researched `locale` a little and it seems it denominates the language code + country. https://en.wikipedia.org/wiki/Language_code
So it's actually `en-US` and not only `en`. https://en.wikipedia.org/wiki/Locale_(computer_software) We only use the language code. `locale` still good?

2020-10-06 20:47 UTC, Tirokk commented on webapp/graphql/Registration.js
> +    $locale: String
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-18T10:18:15Z" title="Friday, October 18th 2019, 12:18:15 pm +02:00">Oct 18, 2019</time>_

---


@roschaefer **language** to **_locale_** change

2020-10-06 20:47 UTC, Tirokk commented
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2019-10-18T13:10:27Z" title="Friday, October 18th 2019, 3:10:27 pm +02:00">Oct 18, 2019</time>_

---



![](https://cdn.dribbble.com/users/756147/screenshots/2953614/final111.gif)

2020-10-08 08:34 UTC, Mogge requested changes
Good catch! I would expect that in case I save sth. upon registration, I can always change this at a later time. So, could the `LocaleSwitch` send a backend request in case you are authenticated?

![good catch](https://media.giphy.com/media/Z9WbnMLSvYfIFprYQv/giphy.gif)

2020-10-08 08:34 UTC, Mogge approved these changes
Yes! Looks great, feel free to merge it if it passes the build @ogerly

2020-10-08 12:39 UTC, closed without merging