overflow: hidden on body removed when popover
Human-Connection-Community/Human-Connection-New-20201003 pull request #2048
Opened 2020-10-05 08:19 UTC by Tirokk

> [<img alt="leternoz" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/leternoz) **Authored by [leternoz](https://github.com/leternoz)**
_<time datetime="2019-10-27T23:11:34Z" title="Monday, October 28th 2019, 12:11:34 am +01:00">Oct 28, 2019</time>_
_Closed <time datetime="2019-12-06T12:52:56Z" title="Friday, December 6th 2019, 1:52:56 pm +01:00">Dec 6, 2019</time>_
---

## 🍰 Pullrequest

The CSS property `overflow: hidden` was set on the `body` when the pointer hover the avatar. I don't know if this was done on purpose, but by removing it, now it doesn't hide the scrollbar.

![Screenshot_20191028_000643](https://user-images.githubusercontent.com/29784958/67643363-eea68d00-f916-11e9-85e9-c031d37b6dfc.png)

### Issues
- fixes #1857

### Todo

- [X] None

2020-10-06 21:54 UTC, Tirokk commented
> [<img alt="alina-beck" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2019-10-30T09:02:19Z" title="Wednesday, October 30th 2019, 10:02:19 am +01:00">Oct 30, 2019</time>_

---


Ah, I think we added `overflow: hidden` to the body to make sure there was no weird scroll behavior when the `notifications menu` and `categories filter` was open! Check this bug: #1413 

Do you think there is any other way to fix this? Or maybe we need a setting to only set `overflow: hidden` for the notifications menu and categories filter? Or use different components altogether? Hmm...

2020-10-06 21:54 UTC, Tirokk commented
> [<img alt="leternoz" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/leternoz) **Authored by [leternoz](https://github.com/leternoz)**
_<time datetime="2019-10-30T15:32:22Z" title="Wednesday, October 30th 2019, 4:32:22 pm +01:00">Oct 30, 2019</time>_

---


I tested on Chromium 78 and Firefox 70, it doesn't seem to have any weird behavior with the scrolling.  

Otherwise, I think, if we would like to have different behavior on `hover` for the `notification menu` and `categories filter`, and the avatar's `post card`, we would have to add an input to the `dropdown` component, to indicate if we want the `overflow: hidden` or not when it is opened.
![Human Connection - Human Connection](https://user-images.githubusercontent.com/29784958/67868412-3fdb9a00-fb2c-11e9-9f5e-bc6a186c8656.gif)

2020-10-07 05:35 UTC, Tirokk commented
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-20T11:14:06Z" title="Wednesday, November 20th 2019, 12:14:06 pm +01:00">Nov 20, 2019</time>_

---


@leternoz @roschaefer ... will we close this then? or leave it open?

2020-10-07 05:46 UTC, Tirokk commented
> [<img alt="leternoz" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/leternoz) **Authored by [leternoz](https://github.com/leternoz)**
_<time datetime="2019-11-28T17:21:45Z" title="Thursday, November 28th 2019, 6:21:45 pm +01:00">Nov 28, 2019</time>_

---


Sorry for the late answer. This PR is not fixing the problem, and I don't think I will have the time to work on it. The required solution is a bit more complex, it would require further analysis to evaluate the depth of the changes to bring.
So in the meanwhile, I suggest to close this PR.

2020-10-07 05:56 UTC, Tirokk commented
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-12-06T12:52:56Z" title="Friday, December 6th 2019, 1:52:56 pm +01:00">Dec 6, 2019</time>_

---


![cry](https://media.giphy.com/media/M28rUlcjueKUE/giphy.gif)

That's sooo sad! But I will close as @leternoz suggested.

@leternoz please tell us if we can help you out. I would love not to loose your effort unmerged. Have you found your way into https://human-connection.org/discord already?

2020-10-08 08:37 UTC, Mogge requested changes
Hey @leternoz big thanks for taking a stab on this issue! :heart: 

Unfortunately I can see the bug that @alina-beck was taking about:

This is `master`:

![output2](https://user-images.githubusercontent.com/2110676/67953163-e6886f00-fbee-11e9-895a-9a457aa719ef.gif)

This is `fix-1857`:

![output](https://user-images.githubusercontent.com/2110676/67953340-35360900-fbef-11e9-8f5e-bd353d2e7c1a.gif)


I guess we really need to refactor the notifications menu. :disappointed:

2020-10-08 12:43 UTC, closed without merging