lower case the email
Human-Connection-Community/Human-Connection-New-20201003 pull request #2100
Opened 2020-10-05 08:34 UTC by Tirokk

> [<img alt="Kachulio1" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Kachulio1) **Authored by [Kachulio1](https://github.com/Kachulio1)**
_<time datetime="2019-10-31T18:01:45Z" title="Thursday, October 31st 2019, 7:01:45 pm +01:00">Oct 31, 2019</time>_
_Closed <time datetime="2019-11-05T23:33:28Z" title="Wednesday, November 6th 2019, 12:33:28 am +01:00">Nov 6, 2019</time>_
---

## 🍰 Pull request

Sets the user email to lower case to avoid case sensitive mismatch 

### Issues

- None

### Todo

- [X] None

2020-10-06 21:59 UTC, Tirokk commented on backend/src/schema/resolvers/passwordReset.js
> +      return createPasswordReset({ driver, nonce, lowerCasedEmail })
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T21:15:07Z" title="Monday, November 4th 2019, 10:15:07 pm +01:00">Nov 4, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -34,7 +34,8 @@ export default {
   Mutation: {
     requestPasswordReset: async (_parent, { email }, { driver }) => {
       const nonce = uuid().substring(0, 6)
-      return createPasswordReset({ driver, nonce, email })
+      const lowerCasedEmail = email.toLowerCase()
+      return createPasswordReset({ driver, nonce, lowerCasedEmail })
```


This is not going to work as `email` and not `lowerCaseEmail` gets desctructured here: https://github.com/Human-Connection/Human-Connection/blob/master/backend/src/schema/resolvers/passwordReset.js#L5

2020-10-06 21:59 UTC, Tirokk commented on backend/src/schema/resolvers/passwordReset.js
> +      return createPasswordReset({ driver, nonce, lowerCasedEmail })
> [<img alt="Kachulio1" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Kachulio1) **Authored by [Kachulio1](https://github.com/Kachulio1)**
_<time datetime="2019-11-04T21:19:19Z" title="Monday, November 4th 2019, 10:19:19 pm +01:00">Nov 4, 2019</time>_

---


Yep, good catch will fix that.

2020-10-06 21:59 UTC, Tirokk commented on backend/src/schema/resolvers/passwordReset.js
> +      return createPasswordReset({ driver, nonce, lowerCasedEmail })
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-04T23:56:20Z" title="Tuesday, November 5th 2019, 12:56:20 am +01:00">Nov 5, 2019</time>_

---


https://github.com/Human-Connection/Human-Connection/pull/2118 :point_left:

2020-10-07 05:11 UTC, Tirokk commented
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-11-05T23:33:28Z" title="Wednesday, November 6th 2019, 12:33:28 am +01:00">Nov 6, 2019</time>_

---


I'm going to close this in favour of #2118 hope you don't mind @Kachulio1 ?

2020-10-08 08:38 UTC, Mogge requested changes
We don't have automated tests for correct email delivery so we need to test this manually. I believe this is borken :thinking:

2020-10-08 12:44 UTC, closed without merging