Added Empty Definitions For Missing Getters And Mutations
Human-Connection-Community/Human-Connection-New-20201003 pull request #2197
Opened 2020-10-05 08:57 UTC by Tirokk

> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2019-11-11T20:23:01Z" title="Monday, November 11th 2019, 9:23:01 pm +01:00">Nov 11, 2019</time>_
_Merged <time datetime="2019-11-12T14:54:46Z" title="Tuesday, November 12th 2019, 3:54:46 pm +01:00">Nov 12, 2019</time>_
---

### Issues
- fixes #2195

2020-10-07 05:15 UTC, Tirokk commented on webapp/pages/index.spec.js
> +        'posts/currentPosts': () => [],
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-11T23:39:32Z" title="Tuesday, November 12th 2019, 12:39:32 am +01:00">Nov 12, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -53,6 +54,7 @@ describe('PostIndex', () => {
         'auth/user': () => {
           return { id: 'u23' }
         },
+        'posts/currentPosts': () => jest.fn(),
```


```suggestion
        'posts/currentPosts': () => [],
```

2020-10-07 05:15 UTC, Tirokk commented on webapp/pages/index.spec.js
> +        'posts/currentPosts': () => [],
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2019-11-12T10:21:40Z" title="Tuesday, November 12th 2019, 11:21:40 am +01:00">Nov 12, 2019</time>_

---


done

2020-10-08 08:38 UTC, Mogge requested changes
Looks good @Mogge, I'd suggest returning an empty array, as that's he default

2020-10-08 08:41 UTC, Mogge requested changes
Looks good @Mogge, I'd suggest returning an empty array, as that's he default

2020-10-08 08:41 UTC, Mogge approved these changes
great job @Mogge !!
thanks a lot :blush:

2020-10-08 12:48 UTC, closed without merging