Get rid of inconsistency with neode setup
Human-Connection-Community/Human-Connection-New-20201003 pull request #2404
Opened 2020-10-05 12:02 UTC by Tirokk

> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-12-02T23:23:55Z" title="Tuesday, December 3rd 2019, 12:23:55 am +01:00">Dec 3, 2019</time>_
_Merged <time datetime="2019-12-10T10:04:36Z" title="Tuesday, December 10th 2019, 11:04:36 am +01:00">Dec 10, 2019</time>_
---

## 🍰 Pullrequest

    Implement getDriver() and getNeode() the same way

    I want to introduce `neode` and `neo4j-graphql-js` to my students and
    saw this.
------
    Fix cypress tests

    Since `dotenv` in the backend now loads configuration from a file
    relative to the current file, we don't have to duplicate the neo4j
    configuration settings here.

2020-10-07 05:50 UTC, Tirokk commented
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2019-12-02T23:50:45Z" title="Tuesday, December 3rd 2019, 12:50:45 am +01:00">Dec 3, 2019</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2810/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">48</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/2810/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | a3251710fa |
| **Started** | Dec 10, 2019 8:58 AM |
| **Ended** | Dec 10, 2019 9:12 AM |
| **Duration** | 14:00 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 78 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/chromium/chromium_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/2810/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

2020-10-07 05:55 UTC, Tirokk commented on backend/src/middleware/hashtags/hashtagsMiddleware.spec.js
> +        neode,
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-12-06T09:15:44Z" title="Friday, December 6th 2019, 10:15:44 am +01:00">Dec 6, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -36,7 +36,7 @@ beforeAll(() => {
     context: () => {
       return {
         user: authenticatedUser,
-        neode: instance,
+        neode: neode,
```


```suggestion
        neode,
```
can't we use ES6 syntax here?

2020-10-07 05:55 UTC, Tirokk commented on backend/src/schema/resolvers/users/blockedUsers.spec.js
> +        neode,
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-12-06T09:17:11Z" title="Friday, December 6th 2019, 10:17:11 am +01:00">Dec 6, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -20,7 +20,7 @@ beforeEach(() => {
       return {
         user: authenticatedUser,
         driver,
-        neode: instance,
+        neode: neode,
```


```suggestion
        neode,
```
same as :point_up_2:

2020-10-08 08:43 UTC, Mogge requested changes
Looks good, just requested two small changes @roschaefer

2020-10-08 08:46 UTC, Mogge approved these changes

2020-10-08 12:54 UTC, closed without merging