Should fix #234 + refactor domain to hostname
Human-Connection-Community/Human-Connection-New-20201003 pull request #243
Opened 2020-10-04 18:35 UTC by Tirokk

> [<img alt="Mastercuber" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mastercuber) **Authored by [Mastercuber](https://github.com/Mastercuber)**
_<time datetime="2019-03-25T12:18:06Z" title="Monday, March 25th 2019, 1:18:06 pm +01:00">Mar 25, 2019</time>_
_Merged <time datetime="2019-03-25T16:05:59Z" title="Monday, March 25th 2019, 5:05:59 pm +01:00">Mar 25, 2019</time>_
---

close #234

2020-10-06 11:13 UTC, Tirokk commented on backend/src/activitypub/ActivityPub.js
> -      activityPub = new ActivityPub(url.hostname || 'localhost', url.port || 4000, url.origin)
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-25T13:47:15Z" title="Monday, March 25th 2019, 2:47:15 pm +01:00">Mar 25, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -33,7 +33,9 @@ export default class ActivityPub {
     if (!activityPub) {
       dotenv.config()
       const url = new URL(process.env.GRAPHQL_URI)
-      activityPub = new ActivityPub(url.hostname || 'localhost', url.port || 4000, url.origin)
+      // TODO Check why the hostname attribute in the prod env not containing the tld! Following line is a quick fix!!
```


@mastercuber I would like to fix this *the clean way:tm:*

2020-10-06 11:13 UTC, Tirokk commented
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-25T13:52:04Z" title="Monday, March 25th 2019, 2:52:04 pm +01:00">Mar 25, 2019</time>_

---


@Mastercuber I updated the description. You can close issues via keywords on Github.

2020-10-06 11:13 UTC, Tirokk commented on backend/src/activitypub/ActivityPub.js
> -      activityPub = new ActivityPub(url.hostname || 'localhost', url.port || 4000, url.origin)
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-03-25T13:56:22Z" title="Monday, March 25th 2019, 2:56:22 pm +01:00">Mar 25, 2019</time>_

---


https://nodejs.org/api/url.html#url_url_host this seems to be the clean fix.

2020-10-08 08:03 UTC, Mogge requested changes
@Mastercuber I think you need some help here. I'll jump in

2020-10-08 08:03 UTC, Mogge approved these changes

2020-10-08 11:43 UTC, closed without merging