Changes Text For SignUp
Human-Connection-Community/Human-Connection-New-20201003 pull request #2678
Opened 2020-10-05 12:40 UTC by Tirokk

> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-06T16:26:05Z" title="Monday, January 6th 2020, 5:26:05 pm +01:00">Jan 6, 2020</time>_
_Merged <time datetime="2020-01-07T20:47:21Z" title="Tuesday, January 7th 2020, 9:47:21 pm +01:00">Jan 7, 2020</time>_
---

## 🍰 Pullrequest

### Issues
- fixes #2659 

### Todo

- [X] None

2020-10-07 07:04 UTC, Tirokk commented
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-01-06T17:02:13Z" title="Monday, January 6th 2020, 6:02:13 pm +01:00">Jan 6, 2020</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3569/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">50</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/3569/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | c6f558524b |
| **Started** | Jan 6, 2020 5:16 PM |
| **Ended** | Jan 6, 2020 5:28 PM |
| **Duration** | 11:33 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Chromium 79 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/chromium/chromium_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/3569/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

2020-10-07 07:05 UTC, Tirokk commented on webapp/locales/en.json
> +          "description": "To get started, you can register here for free:",
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-01-07T10:44:12Z" title="Tuesday, January 7th 2020, 11:44:12 am +01:00">Jan 7, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -30,7 +30,7 @@
         "unavailable": "Unfortunately, public registration of user accounts is not available right now on this server.",
         "title": "Join Human Connection!",
         "form": {
-          "description": "To get started, enter your e-mail address:",
+          "description": "To get started, you can register here for free:",
```


I'm ok with the English @Mogge

2020-10-08 08:50 UTC, Mogge requested changes
please change the title of the `PR` so that it reflects what the `PR` actually fixes
this saves time for reviewers and manual testers, plus it makes it clear in our auto-generated changelog what the `PR` fixes. Thanks :grin:

2020-10-08 08:50 UTC, Mogge approved these changes

2020-10-08 13:04 UTC, closed without merging