fix: Error pages can be translated
Human-Connection-Community/Human-Connection-New-20201003 pull request #2826
Opened 2020-10-05 13:01 UTC by Tirokk

> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-17T17:33:40Z" title="Friday, January 17th 2020, 6:33:40 pm +01:00">Jan 17, 2020</time>_
_Merged <time datetime="2020-02-07T10:59:34Z" title="Friday, February 7th 2020, 11:59:34 am +01:00">Feb 7, 2020</time>_
---

## 🍰 Pullrequest
![grafik](https://user-images.githubusercontent.com/15882241/72632995-d1062400-3957-11ea-8621-ab62394f3d9d.png)

### Issues
- fixes #2409

2020-10-07 07:30 UTC, Tirokk commented
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-17T17:36:37Z" title="Friday, January 17th 2020, 6:36:37 pm +01:00">Jan 17, 2020</time>_

---


@alina-beck do you have suggestions for a better layout. May be a nice image ...

2020-10-07 07:30 UTC, Tirokk commented
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-01-17T17:58:54Z" title="Friday, January 17th 2020, 6:58:54 pm +01:00">Jan 17, 2020</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4622/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">53</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/4622/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | c86132de21 |
| **Started** | Jan 29, 2020 10:32 AM |
| **Ended** | Jan 29, 2020 10:45 AM |
| **Duration** | 12:29 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Electron 78 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/electron/electron_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/4622/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

2020-10-07 07:33 UTC, Tirokk commented
> [<img alt="alina-beck" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2020-01-20T09:47:45Z" title="Monday, January 20th 2020, 10:47:45 am +01:00">Jan 20, 2020</time>_

---


yeah, an image would be nice – you could check the `/static/img/` folder to see if you can find one that fits?

2020-10-07 07:33 UTC, Tirokk commented
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-20T10:32:04Z" title="Monday, January 20th 2020, 11:32:04 am +01:00">Jan 20, 2020</time>_

---


Now it looks like this:
![image](https://user-images.githubusercontent.com/15882241/72719560-62ec7780-3b78-11ea-81b1-7acbfebc63fc.png)

I took the `exclamation-circle` icon.
That do you think @alina-beck ?

2020-10-07 07:33 UTC, Tirokk commented
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-20T12:15:45Z" title="Monday, January 20th 2020, 1:15:45 pm +01:00">Jan 20, 2020</time>_

---


One question. There are some 403 from webapp middleware. Should they be localised too?
There seems to be a generated 404 which so far I could not find in the Codebase. It appears when there is an URL which is not mapped at all. Where could I find this message?

2020-10-07 07:52 UTC, Tirokk commented on webapp/layouts/error.vue
> +    <span class="error-message">{{ $t(message) }}</span>
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-24T13:51:28Z" title="Friday, January 24th 2020, 2:51:28 pm +01:00">Jan 24, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -0,0 +1,34 @@
+<template>
+  <div class="error-container">
+    <base-icon class="error-icon" name="exclamation-circle" />
+    <br />
+    <span v-if="error.message === 'This page could not be found'" class="error-message">
```


I was not able to locate the place where the default 404 error message comes from. So I catch it here. Any ideas?

2020-10-07 07:52 UTC, Tirokk commented on webapp/layouts/error.vue
> +    <span class="error-message">{{ $t(message) }}</span>
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-24T14:13:23Z" title="Friday, January 24th 2020, 3:13:23 pm +01:00">Jan 24, 2020</time>_

---


You could dispatch the error code:

```js
computed: {
  message() {
    const mapping = {
       403: 'error-pages.not-authorized',
       404: // ...
       500: // ...
    }
    const key = mapping(this.error.code) || 'error.default'
    return this.$(key)
  }
}

2020-10-07 07:52 UTC, Tirokk commented on webapp/middleware/isAdmin.js
> +    return error({ statusCode: 403, message: 'error-pages.not-authorized' })
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-24T14:15:35Z" title="Friday, January 24th 2020, 3:15:35 pm +01:00">Jan 24, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -1,5 +1,5 @@
 export default ({ store, error }) => {
   if (!store.getters['auth/isAdmin']) {
-    return error({ statusCode: 403 })
+    return error({ statusCode: 403, message: 'error-pages.not-authorized' })
```


I'm having difficulties with `message` here. It's not the message, it's the translation key.

So, on the consuming side, I would check if there is a translation key for `error.message` (check if it's a key or if the error message is coming from NuxtJS). Just to make sure that we're not trying to translate a default Nuxt error message here.

2020-10-07 07:55 UTC, Tirokk commented on webapp/layouts/error.vue
> +}
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-28T21:06:57Z" title="Tuesday, January 28th 2020, 10:06:57 pm +01:00">Jan 28, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -0,0 +1,50 @@
+<template>
+  <div class="error-container">
+    <img class="error-image" :src="image" />
+    <br />
+    <span v-if="error.message === 'This page could not be found'" class="error-message">
+      {{ $t('error-pages.default') }}
+    </span>
+    <span v-else class="error-message">{{ $t(error.message) }}</span>
+    <br />
+    <nuxt-link to="/">{{ $t('error-pages.back-to-index') }}</nuxt-link>
+  </div>
+</template>
+
+<script>
+export default {
+  props: ['error'],
+  computed: {
+    message() {
+      const mapping = {
+        403: 'error-pages.403-default',
+        404: 'error-pages.404-default',
+        500: 'error-pages.500-default',
+        503: 'error-pages.503-default',
+      }
+      return this.error.key || mapping[this.error.statusCode] || 'error-pages.default'
+    },
+    image() {
+      return `/img/svg/errors/error${this.error.statusCode ? this.error.statusCode : '500'}.svg`
```


```suggestion
      return `/img/svg/errors/error${this.error.statusCode || '500'}.svg`
```

2020-10-07 07:55 UTC, Tirokk commented on webapp/locales/de.json
> +	"cannot-edit-post": "Dieser Beitrag kann nicht editiert werden",
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-01-28T21:07:08Z" title="Tuesday, January 28th 2020, 10:07:08 pm +01:00">Jan 28, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -798,5 +798,16 @@
         "donations-for": "Spenden für",
         "donate-now": "Jetzt spenden",
         "amount-of-total": "{amount} von {total} € erreicht"
+    },
+    "error-pages" : {
+	"profile-not-found": "Dieses Profil konnte nicht gefunden werden",
+	"back-to-index": "Zurück zur Startseite",
+	"post-not-found": "Dieser Beitrag konnte nicht gefunden werden",
+        "cannot-edit-post": "Dieser Beitrag kann nicht editiert werden",
```


Fix indentation

2020-10-07 07:55 UTC, Tirokk commented on webapp/layouts/error.vue
> +}
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-01-28T21:28:21Z" title="Tuesday, January 28th 2020, 10:28:21 pm +01:00">Jan 28, 2020</time>_

---


@roschaefer I thought you wanted an image :)

2020-10-08 08:54 UTC, Mogge requested changes
![Screenshot - 2020-01-28T221535 452](https://user-images.githubusercontent.com/2110676/73306424-7a80cb80-421c-11ea-94bf-beea30e45416.png)
![Screenshot - 2020-01-28T221518 658](https://user-images.githubusercontent.com/2110676/73306425-7a80cb80-421c-11ea-919f-a45566d52a45.png)


Maybe a little large?

![blown away](https://media.giphy.com/media/gZBYbXHtVcYKs/giphy.gif)

2020-10-08 09:04 UTC, Mogge approved these changes
Alright I haven't looked how the error pages look now but I can see from the code that everything is gonna be OK.

![everything is gonna be OK](https://media.giphy.com/media/3o6ZsTRMwQcd0EKWQM/giphy.gif)

2020-10-08 13:09 UTC, closed without merging