[WIP] feat: comment  toToast Messages  is displayed NOT scrolled anymore.
Human-Connection-Community/Human-Connection-New-20201003 pull request #3139
Opened 2020-10-05 15:00 UTC by Tirokk

> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2020-02-22T15:25:36Z" title="Saturday, February 22nd 2020, 4:25:36 pm +01:00">Feb 22, 2020</time>_
_Closed <time datetime="2020-03-11T10:42:28Z" title="Wednesday, March 11th 2020, 11:42:28 am +01:00">Mar 11, 2020</time>_
---

## 🍰 Pullrequest
when responding to a comment of a user a toast is displayed NOT scrolled anymore.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1324583/75094899-a9762d00-558f-11ea-83e4-a5ab4e57767f.gif)

### Issues
- fixes #3000

2020-10-07 09:30 UTC, Tirokk commented
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-02-22T16:01:52Z" title="Saturday, February 22nd 2020, 5:01:52 pm +01:00">Feb 22, 2020</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5532/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5532/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | ece9d3b8b6 |
| **Started** | Feb 22, 2020 8:24 PM |
| **Ended** | Feb 22, 2020 8:45 PM |
| **Duration** | 21:29 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/firefox/firefox_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5532/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

2020-10-07 09:30 UTC, Tirokk commented
> [<img alt="cypress[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/cypress) **Authored by [cypress[bot]](https://github.com/apps/cypress)**
_<time datetime="2020-02-22T16:04:17Z" title="Saturday, February 22nd 2020, 5:04:17 pm +01:00">Feb 22, 2020</time>_

---



<p align="center">
  <br />
  <img src="https://assets.cypress.io/github-pr-comment-icons/cypress-logo.png" height="32" />
</p>

---

### Test summary
<a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5531/specs"><img src="https://assets.cypress.io/github-pr-comment-icons/green-check-mark.png" width="14" height="14" title="Passed" /></a> <b title="Passed">66</b>  &bull; <a href="https://dashboard.cypress.io/projects/qa7fe2/runs/5531/failures"><img src="https://assets.cypress.io/github-pr-comment-icons/red-x.png" width="14" height="14" title="Failed" /></a> <b title="Failed">0</b>  &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/gray-circle.png" width="14" height="14" title="Tests that did not run due to a developer annotating a test with .skip" /> <b title="Pending">0</b> &bull; <img src="https://assets.cypress.io/github-pr-comment-icons/yellow-triangle.png" width="14" height="14" title="Tests that did not run due to a failure in a mocha hook" /> <b title="Skipped">0</b>

---

### Run details
| | |
| --- | --- |
| **Project** | Human-Connection |
| **Status** | Passed |
| **Commit** | 0741218a04 <span style="cursor:help;" title="Your CI provider generated this commit by merging this branch into the target branch.">ℹ️</span> |
| **Started** | Feb 22, 2020 8:24 PM |
| **Ended** | Feb 22, 2020 8:47 PM |
| **Duration** | 22:54 <a href="https://on.cypress.io/parallelization" title="Enable parallelization to reduce run duration">💡</a> |
| **OS** | Linux Ubuntu Linux - 16.04 |
| **Browser** | Firefox 68 <img src="https://cdnjs.cloudflare.com/ajax/libs/browser-logos/48.0.4/firefox/firefox_32x32.png" width="16" height="16" /> |

[View run in Cypress Dashboard ➡️](https://dashboard.cypress.io/projects/qa7fe2/runs/5531/specs)



---

This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/qa7fe2/settings)

2020-10-07 09:35 UTC, Tirokk commented on webapp/components/CommentCard/CommentCard.vue
> +      this.$toast.success(this.$t(`post.comment.addReply`))
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-02-23T14:44:25Z" title="Sunday, February 23rd 2020, 3:44:25 pm +01:00">Feb 23, 2020</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -149,8 +148,9 @@ export default {
       return `#${this.anchor}` === anchor
     },
     reply() {
-      const message = { slug: this.comment.author.slug, id: this.comment.author.id }
+      const message = { slug: this.comment.author.slug + ' ', id: this.comment.author.id }
       this.$emit('reply', message)
+      this.$toast.success(this.$t(`post.comment.addReply`))
```


I really dislike this solution. You get a success message even before a comment has been saved.

2020-10-07 10:19 UTC, Tirokk commented
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2020-03-11T10:42:28Z" title="Wednesday, March 11th 2020, 11:42:28 am +01:00">Mar 11, 2020</time>_

---


this will not be implemented now

2020-10-08 09:05 UTC, Mogge requested changes
I would prefer a human solution over a technical solution. How about telling the user to type in the name? See my comment [here](https://github.com/Human-Connection/Human-Connection/issues/3000#issuecomment-590075771). Is it OK to close this PR unmerged?

2020-10-08 13:19 UTC, closed without merging