2019/kw14/fixed_windows_build_docu_fixed_server_start_text
Human-Connection-Community/Human-Connection-New-20201003 pull request #339
Opened 2020-10-04 18:40 UTC by Tirokk

> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-01T14:37:59Z" title="Monday, April 1st 2019, 4:37:59 pm +02:00">Apr 1, 2019</time>_
_Merged <time datetime="2019-04-01T17:17:27Z" title="Monday, April 1st 2019, 7:17:27 pm +02:00">Apr 1, 2019</time>_
---

Fixed windows build, updated readme (prerequisites & requirements), fixed backend server start log output to reflect proper values

Wrong use of `$npm_config` - see here:
> https://docs.npmjs.com/files/package.json#config
> https://docs.npmjs.com/misc/config
> https://docs.npmjs.com/misc/config#per-package-config-settings
> https://stackoverflow.com/questions/34027400/npm-scripts-config-variables-and-command-substitution-not-working-in-package-j

2020-10-06 11:33 UTC, Tirokk commented on backend/README.md
> +and confirm it's running [here](http://localhost:7474)
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-01T14:55:52Z" title="Monday, April 1st 2019, 4:55:52 pm +02:00">Apr 1, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -63,6 +70,17 @@ docker-compose down -v
 
 Install dependencies:
 
+Download [Neo4j Enterprise Edition](https://neo4j.com/download-center/#releases) and unpack the files.
+
+Download [Neo4j Apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases) and drop the file into the `plugins` folder of the just extratced Neo4j-Server
+
+Start Neo4j
+```
+neo4j\bin\neo4j start
+```
+and confirm it's running [here](http://localhost:7687)
```


```suggestion
and confirm it's running [here](http://localhost:7474)
```

2020-10-06 11:33 UTC, Tirokk commented on backend/README.md
> +Download [Neo4j Apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases) and drop the file into the `plugins` folder of the just extracted Neo4j-Server
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-01T14:56:24Z" title="Monday, April 1st 2019, 4:56:24 pm +02:00">Apr 1, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -63,6 +70,17 @@ docker-compose down -v
 
 Install dependencies:
 
+Download [Neo4j Enterprise Edition](https://neo4j.com/download-center/#releases) and unpack the files.
+
+Download [Neo4j Apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases) and drop the file into the `plugins` folder of the just extratced Neo4j-Server
```


```suggestion
Download [Neo4j Apoc](https://github.com/neo4j-contrib/neo4j-apoc-procedures/releases) and drop the file into the `plugins` folder of the just extracted Neo4j-Server
```

2020-10-06 11:33 UTC, Tirokk commented on backend/README.md
> +Download [Neo4j Community Edition](https://neo4j.com/download-center/#releases) and unpack the files.
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-01T14:56:44Z" title="Monday, April 1st 2019, 4:56:44 pm +02:00">Apr 1, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -63,6 +70,17 @@ docker-compose down -v
 
 Install dependencies:
 
+Download [Neo4j Enterprise Edition](https://neo4j.com/download-center/#releases) and unpack the files.
```


```suggestion
Download [Neo4j Community Edition](https://neo4j.com/download-center/#releases) and unpack the files.
```

2020-10-06 11:33 UTC, Tirokk commented
> [<img alt="ulfgebhardt" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ulfgebhardt) **Authored by [ulfgebhardt](https://github.com/ulfgebhardt)**
_<time datetime="2019-04-01T15:04:55Z" title="Monday, April 1st 2019, 5:04:55 pm +02:00">Apr 1, 2019</time>_

---


> Here are some changes I would like to see, could you also update https://github.com/Human-Connection/Nitro-Documentation ?

Please merge it into the repo first -> https://github.com/Human-Connection/Human-Connection/issues/342

2020-10-06 11:33 UTC, Tirokk commented
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2019-04-01T16:58:58Z" title="Monday, April 1st 2019, 6:58:58 pm +02:00">Apr 1, 2019</time>_

---


@ulfgebhardt I restarted the build. If it passes, feel free to hit the merge button.

2020-10-08 08:04 UTC, Mogge requested changes
Here are some changes I would like to see, could you also update https://github.com/Human-Connection/Nitro-Documentation ?

2020-10-08 08:04 UTC, Mogge approved these changes
Fair enough @ulfgebhardt :handshake:

2020-10-08 11:46 UTC, closed without merging