Create Posts with a specified language, or fallback
Human-Connection-Community/Human-Connection-New-20201003 pull request #795
Opened 2020-10-05 04:40 UTC by Tirokk

> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-10T20:13:17Z" title="Monday, June 10th 2019, 10:13:17 pm +02:00">Jun 10, 2019</time>_
_Merged <time datetime="2019-06-14T16:53:22Z" title="Friday, June 14th 2019, 6:53:22 pm +02:00">Jun 14, 2019</time>_
---

## 🍰 Pullrequest

### Issues

- fixes #781 

### Todo

- [ ] Write component tests for languages

2020-10-06 16:56 UTC, Tirokk commented
> [<img alt="codecov[bot]" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/apps/codecov) **Authored by [codecov[bot]](https://github.com/apps/codecov)**
_<time datetime="2019-06-11T18:47:57Z" title="Tuesday, June 11th 2019, 8:47:57 pm +02:00">Jun 11, 2019</time>_

---


# [Codecov](https://codecov.io/gh/Human-Connection/Human-Connection/pull/795?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@14041ff`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

2020-10-06 17:01 UTC, Tirokk commented
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-12T22:46:12Z" title="Thursday, June 13th 2019, 12:46:12 am +02:00">Jun 13, 2019</time>_

---


![Screenshot at 2019-06-12 19:40:21](https://user-images.githubusercontent.com/26943915/59391432-9d707500-8d4a-11e9-9df1-2b26392869ca.png)
![Screenshot at 2019-06-12 19:40:21](https://user-images.githubusercontent.com/26943915/59391405-8fbaef80-8d4a-11e9-8832-61d9b14ee17f.png)
![Screenshot at 2019-06-12 19:42:19](https://user-images.githubusercontent.com/26943915/59391452-b2e59f00-8d4a-11e9-8dfb-97dff44a2072.png)

2020-10-06 17:02 UTC, Tirokk commented
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-13T23:49:04Z" title="Friday, June 14th 2019, 1:49:04 am +02:00">Jun 14, 2019</time>_

---


![Screenshot at 2019-06-13 17:27:40](https://user-images.githubusercontent.com/26943915/59474315-9fa30400-8e1c-11e9-8442-616cb5362bf9.png)

this is what you would expect @Tirokk??

2020-10-06 17:02 UTC, Tirokk commented on webapp/components/ContributionForm/index.vue
> +          </ds-flex-item>
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-14T07:21:17Z" title="Friday, June 14th 2019, 9:21:17 am +02:00">Jun 14, 2019</time>_

---
> **Outdated (history rewrite)** - original diff
---
```diff
@@ -137,7 +138,10 @@ export default {
       this.$refs.contributionForm.update('content', value)
     },
     returnLocaleName(locale) {
-      if (this.$i18n.locale() === locale.code) {
+      if (
+        (this.contribution && this.contribution.language === locale.code) ||
+        (!this.contribution && this.$i18n.locale() === locale.code)
+      ) {
```


What happens in the else case?

2020-10-06 17:02 UTC, Tirokk commented on webapp/components/ContributionForm/index.vue
> +          </ds-flex-item>
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-14T10:52:34Z" title="Friday, June 14th 2019, 12:52:34 pm +02:00">Jun 14, 2019</time>_

---


good question @Tirokk, I didn't think there was a case where `this.$i8n.locale()` is undefined :thinking: 
what would you expect to happen if there is no locale?

2020-10-06 17:03 UTC, Tirokk commented on webapp/components/ContributionForm/index.vue
> +          </ds-flex-item>
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-06-14T11:23:04Z" title="Friday, June 14th 2019, 1:23:04 pm +02:00">Jun 14, 2019</time>_

---


Just use english as the world language @mattwr18 , I think. Or?
If the else case is not possible, we don’t need an ìf` here?!

2020-10-06 17:03 UTC, Tirokk commented on webapp/components/ContributionForm/index.vue
> +          </ds-flex-item>
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-06-14T16:47:24Z" title="Friday, June 14th 2019, 6:47:24 pm +02:00">Jun 14, 2019</time>_

---


Addressed in our latest pairing session @Tirokk... unfortunately, I forgot to add you as a co-author, but I think you know I appreciate you!!

2020-10-08 08:10 UTC, Mogge approved these changes

2020-10-08 08:10 UTC, Mogge requested changes
There are some function problems:
- If I am in german as a user and I write a post in english, save and edit again, the language is shown as german.
- If I edit the Post again, change the language and save again, the language seems to be still my own and not the language I set.
- Discussable: The language is not shown in the Post, if I don’t edit.

2020-10-08 12:01 UTC, closed without merging